import { PostStatus, ReviewStatus } from '@prisma/client';

export const FALLBACK_CASE_STUDIES = [
  {
    id: 'cs_nexus',
    title: 'Nexus Enterprise Telemetry & AI Routing OS',
    slug: 'nexus-logistics-ai-routing',
    clientName: 'Nexus Global Logistics',
    clientIndustry: 'Logistics & Supply Chain',
    serviceCategory: 'AI Systems & Automation',
    summary: 'Engineered a bespoke 3D web platform paired with automated 24/7 AI quote routing and CRM synchronization.',
    challenge: 'Fragmented inquiries and slow follow-ups were leaking high-value prospects. The client operated on an outdated legacy template with high bounce rates on mobile devices.',
    solution: 'Replaced the legacy stack with a Next.js 15 App Router platform featuring fluid Three.js Silk canvases and crisp editorial typography. In parallel, built an Express & BullMQ worker pipeline that ingests inquiries and runs instant prompt-based qualification.',
    results: 'Eliminated inquiry latency from 18 hours to under 30 seconds. Organic search conversions climbed over 340% within 90 days.',
    metrics: [
      { value: '+340%', label: 'Lead Growth' },
      { value: '< 30s', label: 'AI Response Time' },
      { value: '$1.8M', label: 'Pipeline Generated' },
    ],
    techStack: ['Next.js 15', 'TypeScript', 'Node.js', 'PostgreSQL', 'Three.js', 'Docker'],
    liveUrl: 'https://nexuslogistics.example.com',
    status: PostStatus.PUBLISHED,
    isFeatured: true,
    sortOrder: 1,
    seoTitle: 'Nexus Logistics AI Routing & 3D Platform Case Study | CYBERSTYLE',
    seoDescription: 'How CYBERSTYLE built a 3D Next.js platform and automated AI lead qualification system that increased qualified inquiries by 340%.',
    canonicalUrl: 'https://cyberstyle.agency/work/nexus-logistics-ai-routing',
    keywords: ['Logistics Web Design', 'AI Automation Agency', 'Next.js 15 Case Study', 'Enterprise Telemetry'],
    geoCountry: 'US',
    geoRegion: 'North America',
    geoCity: 'Chicago, IL',
    geoLatitude: 41.8781,
    geoLongitude: -87.6298,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cs_apex',
    title: 'Apex Capital High-Impact Editorial Web Platform',
    slug: 'apex-capital-web-experience',
    clientName: 'Apex Capital Advisory',
    clientIndustry: 'Financial Advisory',
    serviceCategory: 'Full-Stack Web App',
    summary: 'Redesigned brand identity, created fluid interactive Silk visual backgrounds, and boosted conversion velocity.',
    challenge: 'Apex needed an institutional-grade brand presence that projected digital authority while satisfying strict performance requirements for international institutional investors.',
    solution: 'Crafted a custom dark-mode aesthetic with custom GLSL shaders, headless content architecture, and sub-second page transitions.',
    results: 'Achieved a perfect 99/100 Core Web Vitals score on mobile while delivering a 2.4x lift in accredited investor inquiries.',
    metrics: [
      { value: '99/100', label: 'Core Web Vitals' },
      { value: '2.4x', label: 'Investor Inquiries' },
      { value: '0.6s', label: 'Average LCP' },
    ],
    techStack: ['Next.js 15', 'Tailwind CSS', 'GLSL Shaders', 'PostgreSQL', 'Prisma'],
    liveUrl: 'https://apexcapital.example.com',
    status: PostStatus.PUBLISHED,
    isFeatured: true,
    sortOrder: 2,
    seoTitle: 'Apex Capital Financial Platform Case Study | CYBERSTYLE',
    seoDescription: 'Case study on building a high-speed editorial web platform with Three.js shaders for private equity firm Apex Capital.',
    canonicalUrl: 'https://cyberstyle.agency/work/apex-capital-web-experience',
    keywords: ['Fintech Web Design', 'WebGL Development', 'High-Speed Web Platforms', 'Wall Street Agency'],
    geoCountry: 'US',
    geoRegion: 'East Coast',
    geoCity: 'New York, NY',
    geoLatitude: 40.7128,
    geoLongitude: -74.0060,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cs_lumina',
    title: 'Lumina Multi-Tenant Client Operations Portal',
    slug: 'lumina-saas-client-portal',
    clientName: 'Lumina Digital Systems',
    clientIndustry: 'Enterprise SaaS',
    serviceCategory: 'Custom SaaS & Cloud',
    summary: 'Built full-stack operations portal with Argon2id auth, Stripe hosted billing, milestone tracking, and deliverable vault.',
    challenge: 'SaaS client was losing client transparency and wasting 20+ hours per week sending manual billing PDFs and progress emails.',
    solution: 'Engineered a unified multi-tenant operations portal with real-time milestone reviews, Stripe checkout integrations, and encrypted deliverable storage.',
    results: 'Reduced client management overhead by 75% and accelerated invoice settlement speed by 4.2x.',
    metrics: [
      { value: '4.2x', label: 'Faster Payment Settlement' },
      { value: '-75%', label: 'Admin Overhead' },
      { value: '100%', label: 'Deliverable Transparency' },
    ],
    techStack: ['Next.js 15', 'Express.js', 'PostgreSQL', 'Stripe', 'Argon2id', 'Redis'],
    liveUrl: 'https://luminasystems.example.com',
    status: PostStatus.PUBLISHED,
    isFeatured: true,
    sortOrder: 3,
    seoTitle: 'Lumina Multi-Tenant Portal Architecture | CYBERSTYLE',
    seoDescription: 'How CYBERSTYLE built a secure client portal with automated Stripe billing and milestone management.',
    canonicalUrl: 'https://cyberstyle.agency/work/lumina-saas-client-portal',
    keywords: ['Client Portal Development', 'Stripe Integration', 'Custom SaaS Agency', 'Argon2id Auth'],
    geoCountry: 'AE',
    geoRegion: 'MENA',
    geoCity: 'Dubai',
    geoLatitude: 25.2048,
    geoLongitude: 55.2708,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const FALLBACK_REVIEWS = [
  {
    id: 'rev_1',
    clientName: 'Franklin Vance',
    clientTitle: 'Managing Director',
    companyName: 'Apex Capital Advisory',
    rating: 5,
    quote: 'CYBERSTYLE transformed our visual presence completely. Our inbound high-ticket inquiries increased significantly in the first 30 days. Sub-second speed and stunning design.',
    isFeatured: true,
    status: ReviewStatus.APPROVED,
    provenance: 'Direct Feedback',
    consent: true,
    displayPermission: true,
    source: 'client_portal',
    approvedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'rev_2',
    clientName: 'Elena Rostova',
    clientTitle: 'Chief Product Officer',
    companyName: 'OmniFlow Logistics',
    rating: 5,
    quote: 'The custom 3D Silk shader background and automated AI intake workflow tripled our qualified prospect velocity. Exceptional technical rigor and direct builder access.',
    isFeatured: true,
    status: ReviewStatus.APPROVED,
    provenance: 'Direct Feedback',
    consent: true,
    displayPermission: true,
    source: 'client_portal',
    approvedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'rev_3',
    clientName: 'David Chen',
    clientTitle: 'VP of Technology',
    companyName: 'Stratum Ventures',
    rating: 5,
    quote: 'Zero agency bloat or junior account manager telephone games. We worked directly with senior engineers who delivered a 99+ Core Web Vitals build on schedule.',
    isFeatured: true,
    status: ReviewStatus.APPROVED,
    provenance: 'Direct Feedback',
    consent: true,
    displayPermission: true,
    source: 'client_portal',
    approvedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const FALLBACK_FAQS = [
  {
    id: 'faq_1',
    category: 'Build Fees & Scope',
    question: 'How are CYBERSTYLE project fees structured?',
    answer: 'Our projects are priced as fixed one-time build fees based on documented scope: Business Website Launch starts from $750, Website + Smart Enquiry System starts from $1,200, and Custom Web Applications start from $2,500. Every proposal details deliverables in writing before work begins.',
    displayPages: ['faq', 'home', 'pricing'],
    orderIndex: 1,
    isPublished: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'faq_2',
    category: 'Build Fees & Scope',
    question: 'How do milestone payments work?',
    answer: 'Standard projects typically follow a 50% initial milestone payment to initiate design and architecture, with the remaining 50% due upon review, staging acceptance, and final deployment approval. Payments are processed securely via Stripe or bank transfer.',
    displayPages: ['faq', 'home', 'pricing'],
    orderIndex: 2,
    isPublished: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'faq_3',
    category: 'Performance & Engineering',
    question: 'How do you ensure websites perform well on mobile phones?',
    answer: 'We engineer using Next.js and TypeScript, serving pre-rendered HTML and automatically optimizing modern image formats (WebP/AVIF). We avoid bloated third-party plugin suites to guarantee sub-second page loads (99+ Core Web Vitals) and smooth navigation on all cellular connections.',
    displayPages: ['faq', 'home', 'premium-web'],
    orderIndex: 3,
    isPublished: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'faq_4',
    category: 'Automation & AI',
    question: 'What does an AI enquiry workflow do, and what are its limits?',
    answer: 'An automated enquiry assistant can greet visitors, answer routine questions about your services based on approved documentation, and provide links to book consultation calls. It operates under strict guardrails and escalates directly to human staff when complex or out-of-scope inquiries occur.',
    displayPages: ['faq', 'home', 'ai-automation'],
    orderIndex: 4,
    isPublished: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'faq_5',
    category: 'Ownership & Infrastructure',
    question: 'Do I own the code and design files once the project is finished?',
    answer: 'Yes. Upon completion and final settlement, you receive 100% full ownership of custom code repositories, media assets, deployment configurations, and documentation. No proprietary lock-in or recurring builder licensing fees.',
    displayPages: ['faq', 'home', 'pricing', 'premium-web', 'custom-saas'],
    orderIndex: 5,
    isPublished: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'faq_6',
    category: 'Timelines & Delivery',
    question: 'What are typical project timelines from kickoff to launch?',
    answer: 'Standard business websites typically take 2 to 4 weeks, depending on page volume and feedback turnaround. Custom web applications and multi-step automation pipelines typically require 3 to 6 weeks. Target milestone dates are committed in writing.',
    displayPages: ['faq', 'home', 'premium-web', 'custom-saas'],
    orderIndex: 6,
    isPublished: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
